    <table>
      <tr>
        <td>
          Recipe ID
        </td>
        <td>
          <input type='text' name='recipe_id' readonly="readonly" value='<?php echo $data['recipe_id']; ?>' />
        </td>
      </tr>
      <tr>
        <td>
          Item UPC
        </td>
        <td>
          <input type='text' name='item_upc' value='<?php echo $data['item_upc']; ?>' />
        </td>
      </tr>
      <tr>
        <td>
          Item Qty
        </td>
        <td>
          <input type='text' name='item_qty' value='<?php echo $data['item_qty']; ?>' />
        </td>
      </tr>
    </table>