    <table>
      <tr>
        <td>
          UPC
        </td>
        <td>
          <input type='text' name='upc' value='<?php echo $data['upc']; ?>' />
        </td>
      </tr>
      <tr>
        <td>
          Name
        </td>
        <td>
          <input type='text' name='name' value='<?php echo $data['name']; ?>' />
        </td>
      </tr>
      <tr>
        <td>
          Category
        </td>
        <td>
          <input type='text' name='category' value='<?php echo $data['category']; ?>' />
        </td>
      </tr>
    </table>